version: 0.2
        
phases:
  install:
    on-failure: ABORT
    commands:
      - pwd
      - tar -zcf ../django-app.tar.gz .
      - mv ../django-app.tar.gz .
      
artifacts:
  files:
    - django-app.tar.gz